var searchData=
[
  ['s_5fi5g_18820',['s_i5g',['../structs__i5g.html',1,'']]],
  ['s_5fi5g_5finit_18821',['s_i5g_init',['../structs__i5g__init.html',1,'']]],
  ['sd_5fdesc_18822',['sd_desc',['../structsd__desc.html',1,'']]],
  ['sd_5finit_5fparam_18823',['sd_init_param',['../structsd__init__param.html',1,'']]],
  ['spi_5fdesc_18824',['spi_desc',['../structspi__desc.html',1,'']]],
  ['spi_5fdevice_18825',['spi_device',['../structspi__device.html',1,'']]],
  ['spi_5fengine_5fcmd_5fqueue_18826',['spi_engine_cmd_queue',['../structspi__engine__cmd__queue.html',1,'']]],
  ['spi_5fengine_5fdesc_18827',['spi_engine_desc',['../structspi__engine__desc.html',1,'']]],
  ['spi_5fengine_5finit_5fparam_18828',['spi_engine_init_param',['../structspi__engine__init__param.html',1,'']]],
  ['spi_5fengine_5fmsg_18829',['spi_engine_msg',['../structspi__engine__msg.html',1,'']]],
  ['spi_5fengine_5foffload_5finit_5fparam_18830',['spi_engine_offload_init_param',['../structspi__engine__offload__init__param.html',1,'']]],
  ['spi_5fengine_5foffload_5fmessage_18831',['spi_engine_offload_message',['../structspi__engine__offload__message.html',1,'']]],
  ['spi_5finit_5fparam_18832',['spi_init_param',['../structspi__init__param.html',1,'']]],
  ['spi_5fplatform_5fops_18833',['spi_platform_ops',['../structspi__platform__ops.html',1,'']]],
  ['spisettings_5ft_18834',['spiSettings_t',['../structspi_settings__t.html',1,'']]],
  ['std_5ftiming_18835',['std_timing',['../structstd__timing.html',1,'']]],
  ['strg_5fdesc_18836',['strg_desc',['../structstrg__desc.html',1,'']]],
  ['synthlut_18837',['SynthLUT',['../struct_synth_l_u_t.html',1,'']]]
];
